# This code is provided by github.com/dohernandez/dev.

version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/" # Location go.mod
    schedule:
      interval: "daily"
    open-pull-requests-limit: 1
    groups:
      dependencies:
        patterns:
          - "*" # Update all dependencies
        update-types:
          - "minor"
          - "patch"
  - package-ecosystem: gomod
    directory: /testdata
    schedule:
      interval: daily
    open-pull-requests-limit: 1
    groups:
      test-dependencies:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
