plugins:
  - name: dohernandez/storage
    package: github.com/dohernandez/storage
    makefiles_path: makefiles
    main: main.mk
  - name: local
    makefiles_path: makefiles
    main: main.mk
  - name: local-test
    makefiles_path: internal/makefiles
    main: main.mk
