GO ?= go

PWD = $(shell pwd)

# Checking vendor path using plugin variable: PLUGIN_DOHERNANDEZREPOGENERATOR_VENDOR_PATH
ifneq ($(PLUGIN_DOHERNANDEZREPOGENERATOR_VENDOR_PATH),)
	REPO_GENERATOR_DEVGO_PATH = $(PLUGIN_DOHERNANDEZSTORAGE_VENDOR_PATH)
endif

ifeq ($(REPO_GENERATOR_DEVGO_PATH),)
	REPO_GENERATOR_DEVGO_PATH = $(PWD)
endif

REPO_GENERATOR_DEVGO_SCRIPTS ?= $(REPO_GENERATOR_DEVGO_PATH)/makefiles
